apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: frontend
  title: Frontend
  description: Web frontend for the OpenTelemetry Astronomy Shop.

  annotations:
    github.com/project-slug: liyakath07/ultimate-devops-project-demo

spec:
  type: service
  lifecycle: development
  owner: platform-team
  system: astronomy-shop
